# Generated by Django 3.2.3 on 2021-09-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theSmartChurch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
