# Generated by Django 3.2.3 on 2021-09-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theSmartChurch', '0004_alter_congregants_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=200, null=True),
        ),
    ]
