# Generated by Django 3.2.3 on 2021-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theSmartChurch', '0006_alter_wedding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
