# Generated by Django 3.2.3 on 2021-10-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theSmartChurch', '0007_give_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='total',
        ),
    ]
