# Generated by Django 3.2.3 on 2021-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theSmartChurch', '0008_remove_give_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
